### PR TITLE
tabpopup: fix cairo surface leak

### LINKED ISSUE #685: Leaking X resources (on virtual desktop switch?)
#### Expected behaviour
System is responsible even after few weeks of runtime.
After boot zrestop:
```
res-base Wins  GCs Fnts Pxms Misc   Pxm mem  Other   Total   PID Identifier    
0a00000    41    4    2 1686 2248   1181870K     55K 1181926K 11514 marco
2600000    19    6    1   13   92   127387K	 3K 127391K 14352 Mozilla Firefox
```
#### Actual behaviour
After 3 weeks the system takes seconds to do virtual desktop switch or anything.
```
After 15 hours of uptime:
res-base Wins  GCs Fnts Pxms Misc   Pxm mem  Other   Total   PID Identifier    
0a00000    40    4    2 3847 2256   1130430K     55K 1130486K 11514 marco
2600000    27   10    1   19  119   131396K	 4K 131400K 14352 Mozilla Firefox
```
`Pxms` is continually increasing by each virtual desktop switch.

#### Steps to reproduce the behaviour
Runtime of 3 weeks. I have 24 virtual desktops (3840x2160) and switching between them very often.

#### MATE general version
Fedora 34

#### Package version
marco-1.24.2-1.fc34.x86_64

#### Linux Distribution
Fedora 34 x86_64

#### Link to bugreport of your Distribution (requirement)
https://bugzilla.redhat.com/show_bug.cgi?id=1965944
There was [issue 329](https://github.com/mate-desktop/marco/issues/329) but that is probably fixed already.

### PR DESCRIPTION
**Pull request by paravoid**
Commit 6b05da5e49996a2101edfd703dd3f5d91011d726 introduced a Cairo surface leak, by calling `gdk_cairo_surface_create_from_pixbuf()` but then never freeing those surfaces with `cairo_surface_destroy()`.

This manifested in leaking resources when switching between virtual desktops, as observed using xrestop (`Pxms` column), which made the desktop slow and ultimately unusable after a few weeks of uptime.

Fixes #685

### CODE REVIEW

**Comment by paravoid** [comment]
@vkareh, I believe 6b05da5e49996a2101edfd703dd3f5d91011d726 was authored by you, so I'd appreciate your review. Thanks!

**Comment by muktupavels** [comment]
From quick look one more `cairo_surface_destroy` call is missing...

**Comment by pasikarkkainen** [comment]
@paravoid good find! I'm definitely seeing this leak aswell, as marco keeps getting slower and slower as time goes on..

**Comment by jankratochvil** [comment]
@paravoid thanks very much for finding the culprit!!! Here is the fix for the missing leak fix mentioned by @muktupavels . Please note that `cairo_surface_destroy` should be in fact called `cairo_surface_dereference`. I think it can get checked-in both together, right? The numbers are no longer increasing for me:
```
xrestop - Display: localhost:0
          Monitoring 28 clients. XErrors: 0
          Pixmaps: 1551341K total, Other:      97K total, All: 1551439K total
res-base Wins  GCs Fnts Pxms Misc   Pxm mem  Other   Total   PID Identifier    
0a00000    43    4    2   43 2295   1182574K     56K 1182631K 11489 marco
2a00000    28    7    1   27  115   220719K	 4K 220724K 16081 Mozilla Firefox
```
[marco-leak-2.patch.txt](https://github.com/mate-desktop/marco/files/6779222/marco-leak-2.patch.txt)

File: src/ui/draw-workspace.c [hunk 1]
```diff
@@ -131,6 +131,7 @@ draw_window (GtkWidget                   *widget,
       /* If the icon is too big, fall back to mini icon. */
       if (icon_w > (winrect->width - 2) || icon_h > (winrect->height - 2))
         {
+          cairo_surface_destroy(icon);
```
Comment (cwendling) [inline src/ui/draw-workspace.c:134]: style: put a space before the open parenthesis.

File: src/ui/draw-workspace.c [hunk 2]
```diff
@@ -139,6 +140,7 @@ draw_window (GtkWidget                   *widget,
 
               /* Give up. */
               if (icon_w > (winrect->width - 2) || icon_h > (winrect->height - 2))
+                cairo_surface_destroy(icon);
```
Comment (cwendling) [inline src/ui/draw-workspace.c:143]: style: ditto

**Review by cwendling — COMMENTED** [review]
Minor style issue, but more importantly as @muktupavels mentioned there still seem to be a leak of the final icon, that should be fixed by a `cairo_surface_destroy (icon)` around L159.

**Comment by paravoid** [comment]
Thanks all. I updated the commit to address these issues — hope that works.

File: src/ui/draw-workspace.c [hunk 3]
```diff
@@ -139,6 +140,7 @@ draw_window (GtkWidget                   *widget,
 
               /* Give up. */
               if (icon_w > (winrect->width - 2) || icon_h > (winrect->height - 2))
+                cairo_surface_destroy (icon);
                 icon = NULL;
```
Comment (vkareh) [inline src/ui/draw-workspace.c:144]: You're missing parentheses, so you're effectively always setting `icon = NULL`, which means all workspace icons are gone. Similar to:
```
if (icon_w > (winrect->width - 2) || icon_h > (winrect->height - 2))
  {
    cairo_surface_destroy (icon);
  }
icon = NULL;
```
You need to change it to
```suggestion
              if (icon_w > (winrect->width - 2) || icon_h > (winrect->height - 2))
                {
                  cairo_surface_destroy (icon);
                  icon = NULL;
                }
```
(although I suspect the `icon = NULL` is redundant here, but shouldn't hurt)

**Review by vkareh — CHANGES_REQUESTED** [review]

File: src/ui/draw-workspace.c (hunk 3 above)
Comment (paravoid) [reply src/ui/draw-workspace.c:144]: Doh! I hate braceless ifs :) Thanks for catching that, I'll fix!

FWIW, I don't think the `icon = NULL` part is redundant, as there is an `if (icon)` condition below.

**Review by vkareh — APPROVED** [review]
LGTM
