### PR TITLE
Increase icon size on tab and workspace popups

### LINKED ISSUE #333: Alt+tab: icons are too small
#### Actual behaviour
I use Marco with enabled compositor and with disabled windows thumbnails. When I press Alt+tab to switch windows, I see windows icons — they are too small and it is hard to recognize applications.

#### Expected behaviour
Windows icons should be bigger, such as in Metacity.

#### Package version
marco 1.18.1

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/47267316-alt-tab-icons-are-too-small?utm_campaign=plugin&utm_content=tracker%2F841233&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F841233&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #363: Why marco switch-tab icon is so small when composite-manager is disabled
#### Expected behaviour
Make switch-tab icon larger for non composite-manager mode, just like what metacity does.

#### Actual behaviour

The icon is too small to see.

#### Steps to reproduce the behaviour

Using marco as the window manager, and open multiple window, then press "Alt+Tab".

#### MATE general version

all

#### Package version

all

#### Linux Distribution

ubuntu

### PR DESCRIPTION
**Pull request by vkareh**
Alt+Tab and Workspace popups should be sized relative to the screen size.
This way they look nice and large regardless of the display resolution.

Also, given much larger modern resolutions, icon sizes should be larger by default.

Fixes #333 
Fixes #363

### CODE REVIEW

File: src/core/screen.c [hunk 1]
```diff
@@ -1246,20 +1247,25 @@ get_window_pixbuf (MetaWindow *window,
   *width = gdk_pixbuf_get_width (pixbuf);
   *height = gdk_pixbuf_get_height (pixbuf);
 
-  /* Scale pixbuf to max dimension MAX_PREVIEW_SIZE */
+  /* Scale pixbuf to max dimension based on screen sizscreen size */
```
Comment (muktupavels) [inline src/core/screen.c]: I guess you are ignoring multi-monitor setups... For example if I have 3 1280x1024 monitors side by side I would have 3840px screen width. That would be 384px as preview width, no?

Comment (vkareh) [reply src/core/screen.c]: @muktupavels - yes, good point. I'm working on a fix for this.

Comment (vkareh) [reply src/core/screen.c]: okay, I changed it to be based on monitor size, rather than screen size

**Comment by vkareh** [comment]
@lukefromdc - yeah, I can see the huge icons in the workspace switcher in _some_ instances. I think making the switcher itself smaller will scale down the icons, so I will try that.

**Comment by raveit65** [comment]
ui/tabpopup.c has some deprecated GtkMisc warnings, but they are in master already.

**Comment by vkareh** [comment]
@raveit65 - fixed the function prototype (was missing the `void` inside the prototype parameters)

File: src/core/screen-private.h [hunk 2]
```diff
@@ -193,6 +194,8 @@ void          meta_screen_update_workspace_layout (MetaScreen             *scree
 void          meta_screen_update_workspace_names  (MetaScreen             *screen);
 void          meta_screen_queue_workarea_recalc   (MetaScreen             *screen);
 
+GdkMonitor* meta_screen_get_current_monitor (void);
```
Comment (muktupavels) [inline src/core/screen-private.h]: Why this is put here?  Can not it be put in somewhere in `src/ui`?

Comment (vkareh) [reply src/core/screen-private.h]: What would be the difference? (honest question, I actually struggled trying to figure out where to put it)

Comment (muktupavels) [reply src/core/screen-private.h]: I simply think that it is best to limit code availability to place where it is needed. Why put in `screen.c` if it used only in ui? Otherwise there is no functional difference.

**Comment by muktupavels** [comment]
Also is it really needed to go through gdk? You should be able to get this info from `marco` itself...

**Comment by muktupavels** [comment]
@vkareh yes.

**Comment by vkareh** [comment]
@muktupavels - also, why is going through gdk a problem? If I use xinerama, I'm doing a roundtrip to the X server anyway, which is the same that gdk uses internally. Is the problem that GDK would get all this information from scratch, while marco already has it in memory? It almost seems as though I could replace the `XQueryPointer` code with the `GdkDevice`, and not have to maintain that calculation inside marco, but I'm not entirely sure which one is more efficient

**Comment by vkareh** [comment]
There, I pushed a new commit that removes the `meta_screen_get_current_monitor` function and reuses the old `meta_screen_get_current_xinerama`. I kept it as a separate commit in case we don't want it, to not mess around with the previous working commit.

@muktupavels - thoughts?

**Comment by vkareh** [comment]
@muktupavels - cool, thanks!

@raveit65 - are you ok with the new version of the code? I removed the new function and re-used the existing xinerama one.

**Comment by raveit65** [comment]
yeep, i am very happy not to test it again :)

**Comment by lukefromdc** [comment]
Just retested one more time. Good enough, and on small but highdpi screens offers a usability advantage

**Comment by rolandua** [comment]
Is it able to change Alt-Tab previews size somewhere in gtk.css or dconf?
